version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/cronjobs

    steps:
      - checkout
      
      - run:
          name: submit code
          command: |
           sudo yarn global add leetcode-cli
           mkdir -p ~/.lc
           leetcode user -l << EOF
           ${USER}
           ${PASSWORD}
           EOF
           leetcode submit 1.two-sum.127186230.notac.js

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 3"
          filters:
            branches:
              only: master

    jobs:
      - build
