version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/cronjobs

    steps:
      - checkout

      - run:
          name: automated
          command: |
           sudo yarn global add leetcode-cli
           leetcode user -l << EOF
           ${USER}
           ${PASSWORD}
           EOF
           leetcode submit 1.two-sum.127186230.notac.js
